---
- name: Map execution properties dictionary to short alias
  set_fact:
    exec_props: "{{ container_bench_exec_container_benchmark_exec_props }}"

- name: Extract individual properties from exec_props dictionary
  set_fact:
    binary_path: "{{ exec_props.binary_path }}"
    additional_args: "{{ exec_props.additional_args }}"
    exec_time_path: "{{ exec_props.exec_time_path }}"
    rootfull: "{{ exec_props.rootfull }}"

- name: Set common commands (shared across all platforms)
  set_fact:
    image_to_pull: "registry.fedoraproject.org/fedora:42"
    prepare_commands: |
      {{ binary_path }} {{ additional_args }} run --name benchmark_exec -d registry.fedoraproject.org/fedora:42 sleep infinity
    cleanup_commands: |
      {{ binary_path }} {{ additional_args }} stop benchmark_exec
      {{ binary_path }} {{ additional_args }} rm -f benchmark_exec
    benchmark_command: |
      {{ binary_path }} {{ additional_args }} exec benchmark_exec true

- name: Include Unix/Linux tasks
  include_tasks: "../../shared_tasks/unix_default_benchmark_body.yml"
  when: ansible_os_family != 'Windows'

- name: Include Windows tasks
  include_tasks: ../../shared_tasks/windows_default_benchmark_body.yml
  when: ansible_os_family == 'Windows'
