---
- name: Check if the namespace exists
  command:
    oc get namespace "{{ wisdom_deploy_model_namespace }}" -oname
  failed_when: false
  register: namespace_exists

- name: Create the namespace, if it does not exist
  shell: |
    set -o pipefail
    oc new-project {{ wisdom_deploy_model_namespace }}
    oc label namespace {{ wisdom_deploy_model_namespace }} modelmesh-enabled=true --overwrite=true
    oc label namespace {{ wisdom_deploy_model_namespace }} opendatahub.io/dashboard=true --overwrite=true
  when: namespace_exists.rc != 0

- name: Add the modelmesh / odh labels to wisdom namespace
  shell: |
    set -o pipefail
    oc label namespace {{ wisdom_deploy_model_namespace }} modelmesh-enabled=true --overwrite=true
    oc label namespace {{ wisdom_deploy_model_namespace }} opendatahub.io/dashboard=true --overwrite=true

- name: Create the src directory
  file:
    path: "{{ artifact_extra_logs_dir }}/src"
    state: directory
    mode: '0755'

# TODO: Create the S3 and Quay secret using YAML from the vault
- name: Ensure that the S3 secret file exists
  stat:
    path: "{{ wisdom_deploy_model_s3_secret_path }}"

- name: Ensure that the quay secret file exists
  stat:
    path: "{{ wisdom_deploy_model_quay_pull_secret_path }}"

- name: Delete the S3 secret, if it exists
  command: oc delete -f {{ wisdom_deploy_model_s3_secret_path }} --ignore-not-found -n {{ wisdom_deploy_model_namespace }}

- name: Create the S3 secret
  command: oc create -f {{ wisdom_deploy_model_s3_secret_path }} -n {{ wisdom_deploy_model_namespace }}

- name: Delete the quay pull secret, if it exists
  command: oc delete -f {{ wisdom_deploy_model_quay_pull_secret_path }} --ignore-not-found -n {{ wisdom_deploy_model_namespace }}

- name: Create the quay pull secret
  command: oc create -f {{ wisdom_deploy_model_quay_pull_secret_path }} -n {{ wisdom_deploy_model_namespace }}

# model-serving-config ConfigMap:
- name: Apply the ConfigMap "model-serving-config" template
  template:
    src: "{{ model_serving_config_template }}"
    dest: "{{ artifact_extra_logs_dir }}/src/000_model_serving_config.yml"
    mode: '0400'

- name: Create or update the ConfigMap "model-serving-config"
  command: oc apply -f "{{ artifact_extra_logs_dir }}/src/000_model_serving_config.yml"

# ServingRuntime
- name: Apply the ServingRuntime template
  template:
    src: "{{ serving_runtime_template }}"
    dest: "{{ artifact_extra_logs_dir }}/src/001_serving_runtime.yml"
    mode: '0400'

- name: Create or update ServingRuntime
  command: oc apply -f "{{ artifact_extra_logs_dir }}/src/001_serving_runtime.yml"

# InferenceService
- name: Apply the InferenceService template
  template:
    src: "{{ inference_service_template }}"
    dest: "{{ artifact_extra_logs_dir }}/src/002_inference_service.yml"
    mode: '0400'

- name: Create or update InferenceService
  command: oc apply -f "{{ artifact_extra_logs_dir }}/src/002_inference_service.yml"

- name: Patch the service account with the quay pullsecret
  shell: |
    set -o pipefail
    oc patch serviceaccount modelmesh-serving-sa -n {{ wisdom_deploy_model_namespace }} -p '{"imagePullSecrets": [{"name": "quay-io"}]}'
    oc delete pods --all --force -n {{ wisdom_deploy_model_namespace }}


# Wait for wisdom Pods to be ready.
# Max time is 15 minutes to give time for the GPU operator stack and image pull to complete.
- name: Wait for wisdom model mesh Pods to be ready
  block:
  - name: Ensure that wisdom model mesh deployment is ready
    command:
      oc get deployment/modelmesh-serving-{{ wisdom_deploy_model_serving_runtime_name }}
         -n {{ wisdom_deploy_model_namespace }}
         -ojsonpath={.status.unavailableReplicas}
    register: wisdom_number_unavailable
    until:
    - wisdom_number_unavailable.rc == 0
    - not wisdom_number_unavailable.stdout
    retries: 30
    delay: 30

# Put wisdom protos in a Secret
- name: Delete the protos Secret if it already exists
  command: oc delete secret/wisdom-protos --ignore-not-found -n {{ wisdom_deploy_model_namespace }}

- name: Create the wisdom protos Secret
  shell:
    set -o pipefail;
    oc create secret generic wisdom-protos --from-file=$(echo {{ wisdom_deploy_model_protos_path }}/* | tr ' ' ,) -n {{ wisdom_deploy_model_namespace }} --dry-run=client -oyaml | oc apply -f -

- name: Delete the entrypoint ConfigMap if it already exists
  command: oc delete --ignore-not-found configmap/wisdom-tester-entrypoint -n {{ wisdom_deploy_model_namespace }}

- name: Create the entrypoint ConfigMap
  command: oc create configmap wisdom-tester-entrypoint --from-file {{ wisdom_tester_entrypoint }} -n {{ wisdom_deploy_model_namespace }}

- name: Define the test image
  set_fact:
    wisdom_tester_image: image-registry.openshift-image-registry.svc:5000/{{ wisdom_deploy_model_namespace }}/{{ wisdom_deploy_model_tester_imagestream_name }}:{{ wisdom_deploy_model_tester_image_tag }}

- name: Apply the validator Pod template
  template:
    src: "{{ wisdom_tester_pod }}"
    dest: "{{ artifact_extra_logs_dir }}/src/003_wisdom_tester_pod.yml"
    mode: '0400'

- name: Delete the wisdom tester Pod if it exists
  command: oc delete  --ignore-not-found -f "{{ artifact_extra_logs_dir }}/src/003_wisdom_tester_pod.yml" -n {{ wisdom_deploy_model_namespace }}

- name: Create the wisdom tester Pod
  command: oc create -f "{{ artifact_extra_logs_dir }}/src/003_wisdom_tester_pod.yml" -n {{ wisdom_deploy_model_namespace }}

# Wait for model to respond without error
- name: Wait for the wisdom test Pod to terminate
  command:
    oc get pod/wisdom-tester
        -n {{ wisdom_deploy_model_namespace }}
        -o custom-columns=:.status.phase
        --no-headers
  register: tester_wait
  until: tester_wait.stdout == "Succeeded" or tester_wait.stdout == "Error" or tester_wait.stdout == "Failed"
  retries: 10
  delay: 30

- name: Save the wisdom test Pod logs
  shell: oc logs pod/wisdom-tester  -n {{ wisdom_deploy_model_namespace }} > {{ artifact_extra_logs_dir }}/wisdom-tester-pod.log

- name: Ensure that the tester Pod succeeded
  fail: msg="tester Pod failed"
  when: tester_wait.stdout == "Error" or tester_wait.stdout == "Failed"
