---
- name: Run the entitlement test taskbook
  include_role:
    name: entitlement_test_wait_deployment
  when: entitlement_inspect_called_from_testwait == "no"

- name: List entitlement MachineConfig objects
  command: oc get MachineConfig 50-entitlement-key-pem 50-entitlement-pem 50-rhsm-conf
  failed_when: false

- name: List all the MachineConfig objects
  command: oc get MachineConfigs
  failed_when: false

- name: Get the list of MachineConfigPools
  command: oc get MachineConfigPools
  failed_when: false

- name: Get the description of the worker MachineConfigPool
  shell:
    oc describe MachineConfigPool/worker
       > {{ artifact_extra_logs_dir }}/worker_MachineConfigPool.desc
  failed_when: false

- name: Get the description of the master MachineConfigPool
  shell: oc describe MachineConfigPool/master
       > {{ artifact_extra_logs_dir }}/master_MachineConfigPool.desc
  failed_when: false

- name: Get the state of the nodes
  command: oc get nodes
  failed_when: false
