---
- name: Set the number of retry loop to 0 as waiting not requested
  set_fact:
    entitlement_retries: 0
  when: entitlement_test_and_wait != 'yes'

- name: As waiting is requested set the number of retry loop to {{ entitlement_nb_wait_retries }}
  set_fact:
    entitlement_retries: "{{ entitlement_nb_wait_retries }}"
  when: entitlement_test_and_wait == 'yes'

- name: Make sure the entitlement Pod is deployed
  block:
  - name: Wait for the entitlement Pod to succeed
    shell: |
      set -o errexit;
      set -o pipefail;

      oc apply -f "{{ entitlement_tester_entrypoint }}"
      oc delete -f "{{ entitlement_tester_pod }}" --ignore-not-found=true;
      oc create -f "{{ entitlement_tester_pod }}";

      i=0;
      CMD="oc get pod/entitlement-tester
                -o custom-columns=:.status.phase
                --no-headers
                -n default
                ";
      while true; do
          state=$($CMD)
          echo $state
          if echo "$state" | egrep 'Succeeded|Error|Failed'; then
            echo "Done"
            break
          fi
          echo "Waiting for Pod completion ... (#${i})";
          sleep 10;
          i=$(($i+1));
          if [[ "$i" == "12" ]]; then
            echo "Pod took too long to terminate, aborting..."
            exit 1;
          fi;
      done;

      $CMD | egrep 'Succeeded';
    register: entitlement_wait
    until: entitlement_wait.rc == 0
    retries: "{{ entitlement_retries }}"
    delay: 30

  rescue:
  - name: Run the entitlement inspection taskbook
    include_role:
      name: entitlement_inspect
    vars:
      entitlement_inspect_called_from_testwait: "yes"
    when: entitlement_inspect_on_failure == 'yes'

  - name: Store the description of the test Pod (debug)
    shell:
      oc describe pod/entitlement-tester -n default
         > {{ artifact_extra_logs_dir }}/entitlement-test.pod.descr
    failed_when: false

  - name: Failed because the entitlement test Pod did not succeed.
    fail: msg="Failed because the entitlement test Pod did not succeed."

  always:
  - name: Store the test Pod logs (debug)
    shell:
      oc logs pod/entitlement-tester -n default
         > {{ artifact_extra_logs_dir }}/entitlement-test.pod.log
    failed_when: false

  - name: Show the test Pod logs (debug)
    command: oc logs pod/entitlement-tester -n default
    when: _entitlement_testwait_called_from_inspect == "yes" or entitlement_wait.rc != 0
    failed_when: false

  - name: Delete the entitlement tester Pod
    command: oc delete -f "{{ entitlement_tester_pod }}"
    failed_when: false

  - name: Delete the entitlement tester entrypoint
    command: oc delete -f "{{ entitlement_tester_entrypoint }}"
    failed_when: false
