apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      volumes:
      - name: data-dir
        emptyDir: {}
      - name: artifacts-dir
        emptyDir: {}
      - name: empty-bin-dir
        emptyDir: {}
      containers:
      - name: minio
        image: quay.io/minio/minio:RELEASE.2022-05-08T23-50-31Z
        args:
        - server
        - /data
        - --console-address=:9001
        - --anonymous
        ports:
        - containerPort: 9000
        - containerPort: 9001
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - name: data-dir
          mountPath: /data
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            configMapKeyRef:
              name: minio
              key: MINIO_ROOT_USER
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio
              key: MINIO_ROOT_PASSWORD
      - name: ubi8 # this container is used to export data out of the container, with tar/oc cp
        image: quay.io/centos/centos:stream8
        command: [bash, -c]
        args:
        - |
             set -o errexit
             set -o pipefail
             set -o nounset
             set -o errtrace
             set -x
             cd /usr/local/bin
             curl -Ssf "$RSYNC_RPM_URL" | rpm2archive | tar xz ./usr/bin/rsync --strip-components=3
             sleep inf
        env:
        - name: RSYNC_RPM_URL
          value: "http://mirror.centos.org/centos/8-stream/BaseOS/x86_64/os/Packages/rsync-3.1.3-19.el8.x86_64.rpm"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - name: artifacts-dir
          mountPath: /artifacts
        - name: empty-bin-dir
          mountPath: /usr/local/bin
      - name: mc
        image: quay.io/minio/mc:RELEASE.2022-05-09T04-08-26Z
        command: [bash, -cxe]
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - name: artifacts-dir
          mountPath: /artifacts
        args:
        - |
           echo "Waiting for Minio server to launch ..."

           while true; do
             curl -sSf "$MINIO_SERVER_ADDR" > /dev/null || retcode=$?

             [[ $retcode != 7 ]] && break
             sleep 5 # Connection refused, server not ready
           done
           echo "Minio is running, configuring it ..."

           _mc() {
             mc --config-dir /tmp "$@"
           }
           MINIO_SERVER_NAME=minio
           # using 'bash -c' so that the secrets don't get printed by 'set -x'

           # create a local server alias
           bash -c 'echo -e "$MINIO_ROOT_USER\n$MINIO_ROOT_PASSWORD"' \
              | _mc alias set "$MINIO_SERVER_NAME" "$MINIO_SERVER_ADDR"

           # create a user in the server
           bash -c 'echo -e "$MINIO_S3_ACCESS_KEY\n$MINIO_S3_SECRET_KEY"' \
              | _mc admin user add "$MINIO_SERVER_NAME"

           # give privileges to the user
           _mc admin policy set "$MINIO_SERVER_NAME" consoleAdmin "user=$MINIO_S3_ACCESS_KEY"

           # create default bucket
           _mc mb "minio/$MINIO_S3_BUCKET_NAME"

           echo "All done, Minio is configured!"
           sleep +inf
        env:
        - name: MINIO_SERVER_ADDR
          value: http://localhost:9000

        - name: MINIO_ROOT_USER
          valueFrom:
            configMapKeyRef:
              name: minio
              key: MINIO_ROOT_USER

        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio
              key: MINIO_ROOT_PASSWORD

        - name: MINIO_S3_ACCESS_KEY
          valueFrom:
            configMapKeyRef:
              name: minio
              key: MINIO_S3_ACCESS_KEY

        - name: MINIO_S3_BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: minio
              key: MINIO_S3_BUCKET_NAME

        - name: MINIO_S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio
              key: MINIO_S3_SECRET_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  ports:
  - name: s3
    port: 9000
    targetPort: 9000
    protocol: TCP
  - name: console
    port: 9001
    targetPort: 9001
    protocol: TCP
  selector:
    app: minio
