ci_presets:
  # name of the presets to apply, or null if no preset
  name: null
  # list of names of the presets to apply, or a single name, or null if no preset
  names: null

  # run the DSG Notebook scale test
  notebook_scale_test:
    clusters.create.ocp.tags.Project: PSAP/RHODS/scale_test
    tests.notebooks.users.count: 300
    clusters.create.ocp.control_plane.type: m6i.2xlarge
    clusters.create.ocp.workers.type: m6i.2xlarge
    clusters.create.ocp.compute.type: m6i.2xlarge
    tests.notebooks.users.sleep_factor: 3.0
    tests.notebooks.test_flavor: ods-ci
    tests.notebooks.ods_ci.test_case: notebook_dsg_test.robot
    tests.notebooks.repeat: 2
    tests.notebooks.identifier: scale_test

  notebook_scale_test_autoscaling:
    extends: [notebook_scale_test]
    clusters.sutest.compute.autoscaling.enabled: true
    tests.notebooks.repeat: 1

  # run the notebook gating tests
  # (DSG and Jupyter scale tests, notebook performance)
  notebook_gating_scale_test:
    clusters.create.ocp.control_plane.type: m6i.2xlarge
    clusters.create.ocp.workers.type: m6i.2xlarge
    clusters.create.ocp.tags.Project: PSAP/RHODS/gating
    clusters.create.ocp.tags.TicketId: "86"

    tests.notebooks.identifier: gating_test
    tests.notebooks.test_flavor: gating
    # modify the presets, as they will be applied by the gating test
    'ci_presets.notebook_scale_test["matbench.config_file"]': notebook_gating_notebook_scale_test.yaml
    'ci_presets.notebook_performance["matbench.config_file"]': notebook_gating_notebook_performance.yaml
    'ci_presets.notebook_performance["tests.notebooks.notebook_performance.tests[0].instance_types"]': [m6i.2xlarge]
    'ci_presets.notebook_scale_test["tests.notebooks.identifier"]': "notebook_gating_test:scale_test"
    'ci_presets.notebook_performance["tests.notebooks.identifier"]': "notebook_gating_test:performance_test"

  notebook_gating_scale_test_light:
    extends: [notebook_gating_scale_test]
    'ci_presets.notebook_scale_test["tests.notebooks.users.count"]': 5
    'ci_presets.notebook_scale_test["tests.notebooks.repeat"]': 1
    'ci_presets.notebook_performance["clusters.sutest.compute.dedicated"]': false

  notebook_large_scale_test:
    extends: [notebook_scale_test]

    clusters.create.type: ocp
    clusters.create.ocp.tags.Project: PSAP/RHODS/large_scale
    clusters.create.ocp.tags.TicketId: "85"
    clusters.create.ocp.workers.count: 4
    clusters.create.ocp.workers.type: m6i.4xlarge
    clusters.create.ocp.compute.type: m6i.8xlarge
    clusters.driver.compute.autoscaling.enabled: false
    clusters.sutest.compute.machineset.spot: true
    clusters.sutest.compute.autoscaling.enabled: true

    rhods.operator.stop: true
    rhods.operator.dashboard.resources_cpu: 2

    rhods.notebooks.customize.notebook_size.mem_gi: 5

    tests.notebooks.users.count: 2000
    tests.notebooks.users.sleep_factor: 3
    tests.notebooks.repeat: 1

  notebook_large_scale_test_light:
    extends: [notebook_large_scale_test]

    clusters.create.type: single
    tests.notebooks.users.count: 100

  notebook_large_scale_test_no_notebook:
    extends: [notebook_large_scale_test]
    clusters.sutest.compute.machineset.count: 0
    clusters.sutest.compute.machineset.spot: false
    clusters.sutest.compute.autoscaling.enabled: false
    clusters.create.type: single
    tests.notebooks.users.count: 1000

  notebook_fast_scale_test:
    extends: [notebook_scale_test]
    rhods.operator.stop: true
    rhods.operator.odh_notebook_controller.image: null
    rhods.operator.odh_notebook_controller.replicas: 1
    clusters.create.ocp.control_plane.type: m6i.xlarge
    clusters.create.ocp.compute.type: m6i.xlarge

    tests.notebooks.users.count: 300
    tests.notebooks.repeat: 2
    tests.notebooks.users.sleep_factor: 1

  icelake_notebook_scale_test:
    extends: [notebook_scale_test, metal]
    tests.notebooks.users.count: 80
    tests.notebooks.repeat: 1
    tests.notebooks.users.sleep_factor: 1

  icelake_notebook_scale_test_scaleup:
    extends: [notebook_scale_test_scaleup]
    tests.notebooks.users.scaleups: [50, 100, 200, 400, 600, 800]

  icelake_notebook_scale_test_burst:
    extends: [notebook_scale_test_burst]
    tests.notebooks.users.count: 350
    tests.notebooks.ods_ci.test_mode: burst
    tests.notebooks.users.batch_size: 10
    tests.notebooks.users.sleep_factor: 0

  notebook_scale_test_scaleup:
    tests.notebooks.ods_ci.test_mode: scaleup
    tests.notebooks.users.scaleups: [300, 200, 100, 5]
    tests.notebooks.repeat: 1

  notebook_scale_test_burst:
    extends: [notebook_scale_test]
    tests.notebooks.users.count: 2000
    tests.notebooks.ods_ci.test_mode: burst
    tests.notebooks.users.batch_size: 100
    tests.notebooks.users.sleep_factor: 3
    tests.notebooks.ods_ci.stop_notebooks_on_exit: false
    tests.notebooks.repeat: 1

  # run the DSG Notebook scale test with user batching
  notebook_scale_test_batch:
    extends: [notebook_scale_test]
    tests.notebooks.users.batch_size: 10
    tests.notebooks.users.sleep_factor: 5.0

  notebook_scale_test_dsg:
    extends: [notebook_scale_test]
    tests.notebooks.ods_ci.test_case: notebook_dsg_test.robot

  # run the Jupyter Notebook scale test
  notebook_scale_test_jupyter:
    extends: [notebook_scale_test]
    tests.notebooks.ods_ci.test_case: notebook_jupyter_test.robot

  # run the notebook image performance test (dev mode)
  notebook_performance:
    tests.notebooks.test_flavor: notebook-performance
    matbench.config_file: single_notebook_perf.yaml
    matbench.workload: rhods-notebooks-performance
    tests.notebooks.notebook_performance.use_rhods: false
    tests.notebooks.users.count: 1
    clusters.sutest.compute.dedicated: true
    'ci_presets.notebooks_light["clusters.sutest.compute.dedicated"]': true

  # run the notebook image performance test on RHODS (benchmark mode)
  rhods_notebook_performance:
    extends: [notebook_performance]
    tests.notebooks.notebook_performance.use_rhods: true

  notebook_scale_test_burst_create_only:
    extends: [notebook_scale_test]
    tests.notebooks.ods_ci.only_create_notebooks: true
    tests.notebooks.ods_ci.test_mode: burst
    tests.notebooks.users.count: 500
    tests.notebooks.users.batch_size: 100
    tests.notebooks.users.sleep_factor: 3
    tests.notebooks.repeat: 1
    tests.notebooks.ods_ci.stop_notebooks_on_exit: true

  plot.notebook_scale_tests_comparison:
    matbench.preset: notebook_scale_tests_comparison

  cleanup_clusters_on_exit:
    tests.notebooks.cleanup.on_exit.skip_if_le_than_users: 0
    tests.notebooks.cleanup.on_exit.driver.delete_test_namespaces: true
    tests.notebooks.cleanup.on_exit.sutest.uninstall_rhods: true
    tests.notebooks.cleanup.on_exit.sutest.delete_test_namespaces: true
    tests.notebooks.cleanup.on_exit.sutest.uninstall_ldap: true
    tests.notebooks.cleanup.on_exit.sutest.remove_dsg_notebook_dedicated_toleration: true

  # cluster creation presets

  single:
    clusters.create.type: single

  keep:
    clusters.create.keep: true
    clusters.create.ocp.tags.Project: PSAP/RHODS/home-dev

  ocp:
    clusters.create.type: ocp

  osd:
    clusters.create.type: osd
    clusters.sutest.is_managed: true
    clusters.sutest.managed.is_ocm: true

  light_cluster:
    clusters.create.ocp.deploy_cluster.target: cluster_light

  # preset used in CI-provided clusters to limit the scale of the test
  notebooks_light:
    clusters.create.ocp.tags.Project: PSAP/RHODS/ci-dev

    clusters.sutest.compute.dedicated: false
    clusters.sutest.compute.machineset.count: 1

    clusters.driver.compute.dedicated: true
    clusters.driver.compute.machineset.count: 1

    tests.notebooks.users.count: 5
    'ci_presets.notebook_scale_test["tests.notebooks.users.count"]': 5
    'ci_presets.notebook_scale_test_burst_create_only["tests.notebooks.users.count"]': 200
    'ci_presets.notebook_scale_test_burst_create_only["tests.notebooks.users.batch_size"]': 50

  light:
    extends: [light_cluster, notebooks_light]

  metal:
    clusters.sutest.is_metal: true
    clusters.driver.compute.dedicated: false
    clusters.sutest.compute.dedicated: false

  not_metal:
    clusters.sutest.is_metal: false

  fips:
    clusters.create.ocp.use_fips: true

  icelake:
    extends: [metal]
    clusters.driver.compute.dedicated: false
    clusters.sutest.compute.dedicated: false
    'ci_presets.notebook_performance["clusters.sutest.compute.dedicated"]': false
    'ci_presets.notebook_scale_test["tests.notebooks.users.count"]': 150

  spot:
    clusters.sutest.compute.machineset.spot: true
    clusters.sutest.compute.autoscaling.enabled: true
    clusters.driver.compute.machineset.spot: false
    'ci_presets.notebooks_light["clusters.driver.compute.machineset.count"]': null
    'ci_presets.notebooks_light["clusters.driver.compute.dedicated"]': true
    'ci_presets.notebooks_light["clusters.sutest.compute.dedicated"]': true

  perflab_notebook_scale_test:
    extends: [notebook_scale_test, metal, cleanup_clusters_on_exit]
    clusters.driver.compute.dedicated: false
    clusters.sutest.compute.dedicated: false
    tests.notebooks.users.count: 15

  icelake_notebook_scale_test_jenkins:
    extends: [notebook_scale_test, metal, icelake]
    tests.notebooks.users.count: 200

  icelake_notebook_gating_test:
    extends: [notebook_gating_scale_test, metal, icelake]
    tests.notebooks.users.count: 200

  psap_ods_ci:
    tests.notebooks.ods_ci.image.repo: https://github.com/openshift-psap/ods-ci.git
    tests.notebooks.ods_ci.image.ref: notebook-scale-test.v1.30.0-rc1

  help:
    tests.show_help: true
secrets:
  dir:
    name: null
    env_key: PSAP_ODS_SECRET_PATH
  # name of the file containing the properties of LDAP secrets
  s3_ldap_password_file: s3_ldap.passwords
  keep_cluster_password_file: get_cluster.password
  addon_email_file: addon.email
  brew_registry_redhat_io_token_file: brew.registry.redhat.io.token
clusters:
  create:
    type: single # can be: single, ocp, managed
    keep: false
    name_prefix: odsci
    sutest_already_exists:
      hostname: null
      username: null
    ocm:
      version: 4.10.15
      region: us-west-2
      workers:
        type: m5.2xlarge
        count: 2
      compute:
        type: m5.2xlarge
    ocp:
      # list of tags to apply to the machineset when creating the cluster
      tags: {}
      # list of tags to apply to the spot machineset
      spot:
        tags:
          Budget: PSAP
          Project: PSAP
          Environment: TEST/DEV
          Owner: KEVIN POUGET
          Manager: ASHISH KAMRA
          User: kpouget

      deploy_cluster:
        target: cluster
      use_fips: false
      base_domain: psap.aws.rhperfscale.org
      version: 4.12.12
      region: us-west-2
      control_plane:
        type: m6a.xlarge
      workers:
        type: m6a.2xlarge
        count: 2
      compute:
        type: m6i.2xlarge

  cleanup:
    max_age: 4 # hours

  sutest:
    is_metal: false
    is_managed: false
    lab:
      name: null
    managed:
      is_rosa: false
      is_ocm: false
      env: staging
      name: null
    compute:
      dedicated: true
      autoscaling:
        enabled: false
      machineset:
        name: rhods-compute-pods
        count: null
        spot: false
        taint:
          key: only-rhods-compute-pods
          value: "yes"
          effect: NoSchedule
    storage:
      deploy_nfs_provisioner:
        enable: false
        default_sc: true
        pvc_size: 10Gi
        pvc_sc: gp3-csi
  driver:
    compute:
      autoscaling:
        enabled: false
      dedicated: true
      machineset:
        name: test-pods
        count: null
        spot: false
        taint:
          key: &driver_toleration_key only-test-pods
          value: "yes"
          effect: NoSchedule

ldap:
  # Name of the LDAP identity provider.
  idp_name: RHODS_CI_LDAP
  users:
    # number of users to create
    count: 2000
    # prefix of the user names of the LDAP provider
    prefix: psapuser

rhods:
  deploy_from_catalog: true
  catalog:
    image: brew.registry.redhat.io/rh-osbs/iib
    tag: 562218
    channel: beta
    version: 1.32.0 # RC 2
  addon:
    # only necessary/set when rhods.deploy_from_catalog is true
    email: SET_AT_RUNTIME
  notebooks:
    customize:
      enabled: true
      pvc_size: 5Gi
      notebook_size:
        enabled: true
        name: &notebook_size_name Tiny
        cpu: 1
        mem_gi: 4
  operator:
    # set to true to stop the RHODS operator
    stop: false

    odh_notebook_controller:
      image: null
      replicas: null

    notebook_controller_deployment:
      image: null

    dashboard:
      image: null
      replicas: null
      resources_cpu: null

  admin:
    count: 2 # the first N users will be granted these privileges
    roles:
    - view
    - odh-notebook-controller-notebooks-edit
tests:
  # if true, show the list of available presets and exits.
  show_help: false
  notebooks:
    # The test flavor to run. Can be: ods-ci, notebook-performance or gating
    test_flavor: ods-ci
    identifier: unspecified
    minio_bucket_name: notebooks
    # number of test repetition to perform
    repeat: 1
    users:
      # number of users to simulate
      count: 5
      # offset to add to the Pod user index when computing the user name
      start_offset: 0
      # how long to wait between user starts, multiplied by the user index
      sleep_factor: 5.0
      # number of users to launch at the same time
      batch_size: 1
      # numbers of users to launch during the scaleup test
      scaleups: [5, 4, 3, 2, 1]

    # namespace in which the scale test should run
    namespace: notebook-scale-test
    imagestream_name: scale-test
    # Artifacts that should be collected:
    # - 'all': collect all the artifacts generated by ODS-CI.
    # - 'no-screenshot': exclude the screenshots (selenium-screenshot-*.png) from the artifacts collected.
    # - 'no-screenshot-except-zero': exclude the screenshots, except if the job index is zero.
    # - 'no-screenshot-except-failed': exclude the screenshots, except if the test failed.
    # - 'no-screenshot-except-failed-and-zero': exclude the screenshots, except if the test failed or the job index is zero.
    # - 'none': do not collect any ODS-CI artifact.
    artifacts_collected: no-screenshot-except-failed-and-zero
    # Should be true to capture Prometheus databases and properly generate the cluster usage metrics
    # Can be overriden by CI_ARTIFACTS_CAPTURE_PROM_DB
    capture_prom_db: true
    notebook:
      # name of the RHODS notebook size to select when launching the notebook.
      size_name: *notebook_size_name
      # name of the RHODS imagestream to use when launching the notebooks.
      image_name: s2i-generic-data-science-notebook
    ods_ci:
      # ODS-CI test case to execute.
      test_case: notebook_dsg_test.robot
      # mode in which the ODS-CI test should be executed
      # can be: null, simple (default), burst or scaleup
      test_mode: simple
      image:
        repo: https://github.com/red-hat-data-services/ods-ci.git
        ref: master
      # tags to exclude when running the robot test case
      excluded_tags: None
      # if true, only create the notebooks but don't start them
      only_create_notebooks: false
      stop_notebooks_on_exit: true
    test_pods:
      # must be consistent with roles/rhods_notebook_ods_ci_scale_test/templates/ods-ci_job.yaml
      size:
        cpu: 0.2
        mem_gi: 0.75
      toleration: *driver_toleration_key
    ipynb:
      uploaded_directory: testing/notebooks/notebooks
      notebook_filename: benchmark_entrypoint.ipynb
    benchmark:
      # name of the benchmark to pass to the notebook
      name: pyperf_bm_go.py
      # number of times the benchmark should be executed within one repeat.
      number: 20
      # number of repeats of the benchmark to perform.
      repeat: 3
    cleanup:
      on_exit:
        skip_if_le_than_users: 2
        driver:
          # if enable, delete the test namespaces after the testing
          delete_test_namespaces: true
        sutest:
          # if enable, uninstall RHODS
          uninstall_rhods: true
          delete_test_namespaces: true
          uninstall_ldap: true
          remove_dsg_notebook_dedicated_toleration: true

    notebook_performance:
      use_rhods: true
      tests:
      - imagestream: all
        ipynb:
          uploaded_directory: testing/notebooks/notebooks
          notebook_filename: benchmark_entrypoint.ipynb
        instance_types:
        - m6i.xlarge
        benchmarks:
          # name of the benchmark to pass to the notebook
        - name: pyperf_bm_go.py
          # number of times the benchmark should be executed within one repeat.
          number: 20
          # number of repeats of the benchmark to perform.
          repeat: 5
    # List of preset configurations to run as part of the 'gating' test
    gating_tests:
    - notebook_scale_test_dsg
    - notebook_scale_test_jupyter
    - rhods_notebook_performance

matbench:
  preset: null
  workload: rhods-notebooks
  config_file: notebook_scale_test_ods_ci.yaml # visualizations/rhods-notebooks/data
  download:
    mode: prefer_cache
    url:
    url_file:
    # if true, copy the results downloaded by `matbench download` into the artifacts directory
    save_to_artifacts: false
  ignore_exit_code: true
  # directory to plot. Set by notebook_scale_test.sh before launching the visualization
  test_directory: null
