- name: Store OpenShift version identifier
  shell:
    set -o pipefail;
    oc version -o json
       | jq --raw-output '.openshiftVersion'
       > {{ artifact_extra_logs_dir }}/ocp.version

- name: Store OpenShift YAML version
  shell:
    oc version -oyaml
       > {{ artifact_extra_logs_dir }}/ocp_version.yml

- name: Store OpenShift YAML clusterversion
  shell:
    oc get clusterversion/version -oyaml
       > {{ artifact_extra_logs_dir }}/ocp_clusterversion.yml

# ---

- name: Store the OpenShift nodes
  shell:
    oc get nodes -owide
       > {{ artifact_extra_logs_dir }}/nodes.status;
    oc get nodes -oyaml
       > {{ artifact_extra_logs_dir }}/nodes.yaml;

- name: Store the OpenShift machines
  shell:
    oc get machines -n openshift-machine-api -owide
       > {{ artifact_extra_logs_dir }}/machines.status;
    oc get machines -n openshift-machine-api -oyaml
       > {{ artifact_extra_logs_dir }}/machines.yaml;

# ---

- name: Fetch TOPSAIL version from Git
  command:
    git describe HEAD --long --always
  register: git_version

- name: Store TOPSAIL version from Git
  copy:
    content: "{{ git_version.stdout }}"
    dest: "{{ artifact_extra_logs_dir }}/topsail.git_version"
    mode: '0644'

- name: Fetch TOPSAIL last git commit
  command:
    git show --no-patch
  register: git_show

- name: Store TOPSAIL last git commit
  copy:
    content: "{{ git_show.stdout }}"
    dest: "{{ artifact_extra_logs_dir }}/topsail.git_commit"
    mode: '0644'

- name: Get the cluster nodes status
  shell:
    oc get nodes > "{{ artifact_extra_logs_dir }}/nodes.status"

- name: Get the cluster nodes yaml
  shell:
    oc get nodes -oyaml > "{{ artifact_extra_logs_dir }}/nodes.yaml"

- name: Get the cluster nodes json
  shell:
    oc get nodes -ojson > "{{ artifact_extra_logs_dir }}/nodes.json"

- name: Get the cluster nodes description
  shell:
    oc describe nodes > "{{ artifact_extra_logs_dir }}/nodes.descr"

- name: Get the cluster machines status
  shell:
    oc get machines -n openshift-machine-api -owide > "{{ artifact_extra_logs_dir }}/machines.status"

- name: Get the cluster machines yaml
  shell:
    oc get machines -n openshift-machine-api -oyaml > "{{ artifact_extra_logs_dir }}/machines.yaml"

- name: Get the cluster machines description
  shell:
    oc describe machines -n openshift-machine-api > "{{ artifact_extra_logs_dir }}/machines.desc"

- name: Get the cluster CSV
  shell:
    oc get csv -A --show-labels | grep -v olm.copiedFrom > "{{ artifact_extra_logs_dir }}/csv.status"
  ignore_errors: true

- name: Get the cluster CSV in json
  shell:
    oc get csv -A -ojson > "{{ artifact_extra_logs_dir }}/csv.json"
