load_timeline_generator: "roles/load_aware/load_aware_scale_test/files/timeline.py"
pod_start_scheduler: "roles/load_aware/load_aware_scale_test/files/scheduler.py"
coreutils_make_pod: "roles/load_aware/load_aware_scale_test/files/coreutils-make-pod.yaml"
coreutils_test_pod: "roles/load_aware/load_aware_scale_test/files/coreutils-test-pod.yaml"
