---

# TODO: Make the runtime / model version configurable
# TODO: Make instancetype configurable
- name: Create the src directory
  file:
    path: "{{ artifact_extra_logs_dir }}/src"
    state: directory
    mode: '0755'

# Put wisdom protos in a Secret
- name: Delete the protos Secret if it already exists
  command: oc delete secret/wisdom-protos --ignore-not-found -n {{ wisdom_llm_load_test_multiplexed_namespace }}

- name: Create the wisdom protos Secret
  shell:
    set -o pipefail;
    oc create secret generic wisdom-protos --from-file=$(echo {{ wisdom_llm_load_test_multiplexed_protos_path }}/* | tr ' ' ,) -n {{ wisdom_llm_load_test_multiplexed_namespace }} --dry-run=client -oyaml | oc apply -f -

# The results need to be pushed to S3 after the run, put S3 credentials in a Secret
- name: Delete the S3 push secret for results if it exists
  command: oc delete --ignore-not-found secret/llm-load-test-s3-credentials -n {{ wisdom_llm_load_test_multiplexed_namespace }}

- name: Create the S3 push secret for results
  command: oc create secret generic --from-file={{ wisdom_llm_load_test_multiplexed_s3_secret_path }} -n {{ wisdom_llm_load_test_multiplexed_namespace }} llm-load-test-s3-credentials

# The dataset (input to the model) needs to be mounted into the test Pod.
- name: Delete the dataset Secret if it exists
  command: oc delete --ignore-not-found secret/llm-load-test-dataset -n {{ wisdom_llm_load_test_multiplexed_namespace }}

- name: Create the dataset Secret
  command: oc create secret generic llm-load-test-dataset --from-file=dataset.json="{{ wisdom_llm_load_test_multiplexed_dataset_path }}" -n {{ wisdom_llm_load_test_multiplexed_namespace }}
  # The Pod will mount llm-load-test-dataset in /etc/load_test_dataset. The config.json expects the dataset.json at /etc/load_test_dataset/dataset.json.

# Templatize the run configuration into config.json and embed it in a ConfigMap
- name: Delete the llm-load-test config.json ConfigMap if it exists
  command: oc delete --ignore-not-found configmap/llm-load-test-config -n {{ wisdom_llm_load_test_multiplexed_namespace }}

- name: Apply the llm-load-test config.json template
  template:
    src: "{{ llm_load_test_config_template }}"
    dest: "{{ artifact_extra_logs_dir }}/src/000_llm_load_test_config.json"
    mode: '0400'

- name: Create the llm-load-test-config ConfigMap
  command: oc create configmap llm-load-test-config --from-file=config.json="{{ artifact_extra_logs_dir }}/src/000_llm_load_test_config.json" -n {{ wisdom_llm_load_test_multiplexed_namespace }}

- name: Define the test image
  set_fact:
    llm_load_test_image: image-registry.openshift-image-registry.svc:5000/{{ wisdom_llm_load_test_multiplexed_namespace }}/{{ wisdom_llm_load_test_multiplexed_tester_imagestream_name }}:{{ wisdom_llm_load_test_multiplexed_tester_image_tag }}

- name: Apply the validator Pod template
  template:
    src: "{{ llm_load_test_pod_template }}"
    dest: "{{ artifact_extra_logs_dir }}/src/001_llm_load_test_pod.yml"
    mode: '0400'

- name: Delete the llm-load-test Pod if it exists
  command: oc delete --ignore-not-found -f "{{ artifact_extra_logs_dir }}/src/001_llm_load_test_pod.yml" -n {{ wisdom_llm_load_test_multiplexed_namespace }}

- name: Create the llm-load-test Pod
  command: oc create -f "{{ artifact_extra_logs_dir }}/src/001_llm_load_test_pod.yml" -n {{ wisdom_llm_load_test_multiplexed_namespace }}

- name: Wait for llm load test Pod to finish running
  block:
  - name: Ensure that the llm-load-test Pod is complete
    command:
      oc get pod/llm-load-test
         -n {{ wisdom_llm_load_test_multiplexed_namespace }}
         -o custom-columns=:.status.phase
         --no-headers
    register: load_test_wait
    until: load_test_wait.stdout == "Succeeded" or load_test_wait.stdout == "Error" or load_test_wait.stdout == "Failed"
    retries: 20
    delay: 60

- name: Save the llm-load-test Pod logs
  shell: oc logs pod/llm-load-test -n {{ wisdom_llm_load_test_multiplexed_namespace }} > {{ artifact_extra_logs_dir }}/llm-load-test-logs-{{ wisdom_llm_load_test_multiplexed_replicas }}-{{ wisdom_llm_load_test_multiplexed_requests }}-{{ wisdom_llm_load_test_multiplexed_concurrency }}.log

- name: Delete the llm-load-test Pod if it exists
  command: oc delete --ignore-not-found -f "{{ artifact_extra_logs_dir }}/src/001_llm_load_test_pod.yml" -n {{ wisdom_llm_load_test_multiplexed_namespace }}

- name: Ensure that llm-load-test Pod succeeded
  fail: msg="llm-load-test Pod failed"
  when: load_test_wait.stdout == "Error" or load_test_wait.stdout == "Failed"
