ci_presets:
  # name of the presets to apply, or null if no preset
  name: null
  # list of names of the presets to apply, or a single name, or null if no preset
  names: null

  light_cluster:
    clusters.create.ocp.deploy_cluster.target: cluster_light

  ansible_llm_light:
    tests.ansible_llm.test_cases: [[1, 16]]
    tests.ansible_llm.multiplexed_test_cases: [[1, 16]]

  light:
    extends: [light_cluster, ansible_llm_light]

  keep:
    clusters.create.keep: true
    clusters.create.ocp.tags.Project: PSAP/RHODS/Wisdom
    # clusters.create.ocp.tags.TicketId: #TODO

clusters:
  create:
    type: single # can be: single, ocp, managed
    keep: false
    name_prefix: wisdomci
    ocp:
      # list of tags to apply to the machineset when creating the cluster
      tags:
        TicketId: 124
        Project: PSAP/RHODS/Wisdom
      deploy_cluster:
        target: cluster
      base_domain: psap.aws.rhperfscale.org
      version: 4.12.15
      region: us-west-2
      control_plane:
        type: m6a.xlarge
      workers:
        type: m6a.2xlarge
        count: 2
      compute:
        type: m6i.2xlarge
rhods:
  catalog:
    image: brew.registry.redhat.io/rh-osbs/iib
    tag: 537294
    channel: beta
    version: 1.30.0
secrets:
  dir:
    name: psap-ods-secret
    env_key: PSAP_ODS_SECRET_PATH
  # name of the file containing the properties of LDAP secrets
  s3_ldap_password_file: s3_ldap.passwords
  keep_cluster_password_file: get_cluster.password
  brew_registry_redhat_io_token_file: brew.registry.redhat.io.token

tests:
  config:
    tester_imagestream_name: "llm-load-test"
    tester_image_tag: "wisdom-ci"
    test_namespace: "wisdom"
    model_ver: "v11.4.4" # TODO use these
    runtime_ver: "v0.27.0" # TODO use these
    s3_creds_model_secret_path: "/work/secrets/wisdom/s3-secret.yaml"
    quay_secret_path: "/work/secrets/wisdom/quay-secret.yaml"
    protos_path: "/work/secrets/wisdom-protos"
    s3_creds_results_secret_path: "/work/secrets/wisdom/credentials"
    dataset_path: "/work/secrets/wisdom/llm-load-test-dataset.json"
    replicas: 1
    concurrency: 16
    requests: 16
    max_duration: "15m"
  ansible_llm:
    test_cases:
    - [1, 1]
    - [1, 2]
    - [1, 4]
    - [1, 8]
    - [1, 16]
    - [2, 16]
    - [2, 32]
    - [4, 32]
    - [4, 64]
    multiplexed_test_cases:
    - [1, 8]
    - [1, 16]
    - [2, 16]
    - [2, 32]
    - [4, 32]
    - [4, 64]
