---
- name: Validate required variables are defined
  assert:
    that:
      - container_bench_exec_benchmark_exec_time_path is defined
      - container_bench_exec_benchmark_binary_path is defined
      - container_bench_exec_benchmark_rootfull is defined
      - container_bench_exec_benchmark_additional_args is defined
  when: false  # This task never runs but validates variable definitions

- name: Map long variable names to short aliases
  include_tasks: "../../shared_tasks/map_variables.yml"
  vars:
    benchmark_role_name: "container_bench_exec_benchmark"

- name: Set common commands (shared across all platforms)
  set_fact:
    image_to_pull: "registry.fedoraproject.org/fedora:latest"
    prepare_commands: |
      {{ binary_path }} {{ additional_args }} run --name benchmark_exec -d registry.fedoraproject.org/fedora:latest sleep infinity
    cleanup_commands: |
      {{ binary_path }} {{ additional_args }} stop benchmark_exec
      {{ binary_path }} {{ additional_args }} rm -f benchmark_exec
    benchmark_command: |
      {{ binary_path }} {{ additional_args }} exec benchmark_exec true

- name: Include Unix/Linux tasks
  include_tasks: "../../shared_tasks/unix_default_benchmark_body.yml"
  when: ansible_os_family != 'Windows'

- name: Include Windows tasks
  include_tasks: ../../shared_tasks/windows_default_benchmark_body.yml
  when: ansible_os_family == 'Windows'
