apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#namePrefix: codellama-34b-instruct-hf-

resources:
- ../../base

patches:
- path: patch.yaml  
  target:
    kind: InferenceService
    name: isvc
  options:
    allowNameChange: true
