---
# Uninstall (undeploy) NFD
- name: Undeploying NFD operator
  block:
    - name: Attempting to undeploy the NFD operator. Waiting {{ timeout_value_sec }}s...
      make:
        chdir: '{{ nfd_download_path }}'
        target: 'undeploy'
      async: '{{ timeout_value_sec }}'
      poll: 10
      register: nfd_undeployment_output
      failed_when: nfd_undeployment_output.rc == 1
  rescue:
    - name: Undeployment failed 
      debug:
        msg: 'Could not undeploy the operator. Likely, the "nfd-operator" namespace is stuck in terminating. This is an OpenShift issue. Please either increase the "task_timeout" value or try the following solution to force undeployment -- github.com/kubernetes/kubernetes/issues/60807#issuecomment-408599873 -- although you may need to follow instructions here -- github.com/kubernetes/kubernetes/issues/60807#issuecomment-410260006'
    - meta: end_play
