---
- name: Validate required variables are defined
  assert:
    that:
      - container_bench_load_image_benchmark_exec_time_path is defined
      - container_bench_load_image_benchmark_binary_path is defined
      - container_bench_load_image_benchmark_rootfull is defined
      - container_bench_load_image_benchmark_additional_args is defined
  when: false  # This task never runs but validates variable definitions

- name: Map long variable names to short aliases
  include_tasks: "../../shared_tasks/map_variables.yml"
  vars:
    benchmark_role_name: "container_bench_load_image_benchmark"

- name: Set common commands (shared across all platforms)
  set_fact:
    image_to_pull: "docker.io/tensorflow/tensorflow:latest-gpu"
    prepare_commands: |
      {{ binary_path }} {{ additional_args }} save docker.io/tensorflow/tensorflow:latest-gpu -o tensorflow.tar
    benchmark_command: |
      {{ binary_path }} {{ additional_args }} load -i tensorflow.tar

- name: Set Unix/Linux cleanup commands
  set_fact:
    cleanup_commands: "rm -rf tensorflow.tar"
  when: ansible_os_family != 'Windows'

- name: Set Windows cleanup commands
  set_fact:
    cleanup_commands: "Remove-Item -Recurse -Force tensorflow.tar"
  when: ansible_os_family == 'Windows'

- name: Include Unix/Linux tasks
  include_tasks: "../../shared_tasks/unix_default_benchmark_body.yml"
  when: ansible_os_family != 'Windows'

- name: Include Windows tasks
  include_tasks: "../../shared_tasks/windows_default_benchmark_body.yml"
  when: ansible_os_family == 'Windows'
