# ---
# This file will get overwritten by the .j2 templates in ../../templates/
# This is just meant to be an example

# {% if kserve_deploy_model_inference_service_name %}
# - op: replace
#   path: /metadata/name
#   value: {{ kserve_deploy_model_inference_service_name }}
# {% endif %}

# {% if kserve_deploy_model_raw_deployment %}
- op: replace
  path: /metadata/annotations/serving.kserve.io~1deploymentMode
  value: "RawDeployment"
# {% else %}
# - op: replace
#   path: /metadata/annotations/serving.kserve.io~1deploymentMode
#   value: "Serverless"
# - op: replace
#   path: /metadata/annotations/serving.knative.openshift.io~1enablePassthrough
#   value: "true"
# - op: replace
#   path: /metadata/annotations/sidecar.istio.io~1inject
#   value: "true"
# - op: replace
#   path: /metadata/annotations/sidecar.istio.io~1rewriteAppHTTPProbers
#   value: "true"
# {% endif %}"

# Override runtime name, must match name in the ServingRuntime metadata
# {% kserve_deploy_model_sr_name %}
# - op: replace
#   path: /spec/predictor/model/runtime
#   value: {{ kserve_deploy_model_sr_name }}
# {% endif %}"
- op: replace
  path: /spec/predictor/minReplicas
  value: 2 # {{ kserve_deploy_model_inference_service_min_replicas }}
