---
# Reference variables to satisfy validation (they are used dynamically in map_variables.yml)
- name: Validate required variables are defined
  assert:
    that:
      - container_bench_iperf_host_to_container_benchmark_exec_time_path is defined
      - container_bench_iperf_host_to_container_benchmark_binary_path is defined
      - container_bench_iperf_host_to_container_benchmark_rootfull is defined
      - container_bench_iperf_host_to_container_benchmark_additional_args is defined
  when: false  # This task never runs but validates variable definitions

- name: Map long variable names to short aliases
  include_tasks: "../../shared_tasks/map_variables.yml"
  vars:
    benchmark_role_name: "container_bench_iperf_host_to_container_benchmark"

- name: Set benchmark commands
  set_fact:
    image_to_pull: "docker.io/mlabbe/iperf3:3.17.1-r0"
    log_file_name: "iperf_host_to_container.log"
    prepare_commands: |
      {{ binary_path }} {{ additional_args }} run -d -p 5201:5201 --name iperf3-server docker.io/mlabbe/iperf3:3.17.1-r0 -s -d
    cleanup_commands: |
      {{ binary_path }} {{ additional_args }} rm -f iperf3-server
      {{ binary_path }} {{ additional_args }} rmi -f docker.io/mlabbe/iperf3:3.17.1-r0
    benchmark_command: |
      iperf3 -c 127.0.0.1

- name: Include Unix/Linux tasks
  include_tasks: "../../shared_tasks/unix_synthetic_benchmark_body.yml"
  when: ansible_os_family != 'Windows'

- name: Include Windows tasks
  include_tasks: "../../shared_tasks/windows_synthetic_benchmark_body.yml"
  when: ansible_os_family == 'Windows'
