---
- name: Map execution properties dictionary to short alias
  set_fact:
    exec_props: "{{ container_bench_iperf_net_host_benchmark_exec_props }}"

- name: Extract individual properties from exec_props dictionary
  set_fact:
    binary_path: "{{ exec_props.binary_path }}"
    additional_args: "{{ exec_props.additional_args }}"
    exec_time_path: "{{ exec_props.exec_time_path }}"
    rootfull: "{{ exec_props.rootfull }}"

- name: Set sleep command
  set_fact:
    sleep_cmd: "{{ 'Start-Sleep -Seconds 5' if ansible_os_family == 'Windows' else 'sleep 5' }}"

- name: Set benchmark commands
  set_fact:
    image_to_pull: "docker.io/networkstatic/iperf3:latest"
    log_file_name: "iperf_net_host.log"
    prepare_commands: |
      {{ binary_path }} {{ additional_args }} run -d --network=host --name iperf3-server docker.io/networkstatic/iperf3:latest -s -d
      {{ sleep_cmd }}
    cleanup_commands: |
      {{ binary_path }} {{ additional_args }} stop iperf3-server
      {{ binary_path }} {{ additional_args }} rm -f iperf3-server
      {{ binary_path }} {{ additional_args }} rmi -f docker.io/networkstatic/iperf3:latest
    benchmark_command: |
      {{ binary_path }} {{ additional_args }} run --rm --network=host docker.io/networkstatic/iperf3:latest -c 127.0.0.1
- name: Include Unix/Linux tasks
  include_tasks: "../../shared_tasks/unix_synthetic_benchmark_body.yml"
  when: ansible_os_family != 'Windows'

- name: Include Windows tasks
  include_tasks: "../../shared_tasks/windows_synthetic_benchmark_body.yml"
  when: ansible_os_family == 'Windows'
