---
- name: Log whoami
  shell:
    whoami

- name: Save the name of the cluster lock directory
  set_fact:
    cluster_lock_dir: "/tmp/topsail_{{ jump_ci_take_lock_cluster }}"

- name: Create the lock directory
  shell: |
    if mkdir "{{ cluster_lock_dir }}" 2>/dev/null; then
      echo "$(date) Lock '{{ jump_ci_take_lock_cluster }}' acquired.";
      exit 0
    fi

    echo "$(date) Lock '{{ jump_ci_take_lock_cluster }}' already taken ..."
    cat "{{ cluster_lock_dir }}/lock_owner" 2>/dev/null || true
    exit 1

  register: lock_directory_created_cmd
  until: lock_directory_created_cmd.rc == 0
  retries: 9999
  delay: 10

- name: Log info about the lock owner
  shell:
    echo "{{ jump_ci_take_lock_owner }}" > "{{ cluster_lock_dir }}/lock_owner"

- name: Ensure that the lock is owned
  include_role:
    name: jump_ci_ensure_lock
  vars:
    jump_ci_ensure_lock_cluster: "{{ jump_ci_take_lock_cluster }}"
    jump_ci_ensure_lock_owner: "{{ jump_ci_take_lock_owner }}"
