apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: watsonx-e2e-perf # Overwritten by templates

resources:
  - servingruntime.yaml
  - inferenceservice.yaml

configurations:
- configuration.yaml
