ci_presets:
  # name of the presets to apply, or null if no preset
  name: null
  # list of names of the presets to apply, or a single name, or null if no preset
  names: null

  single:
    clusters.create.type: single

  keep:
    clusters.create.keep: true
    clusters.create.ocp.tags.Project: PSAP/RHODS/Pipelines/home-dev
    clusters.create.ocp.tags.TicketId: 87

  light_cluster:
    clusters.create.ocp.deploy_cluster.target: cluster_light

  light:
    extends: [light_cluster]

  metal:
    clusters.sutest.is_metal: true
    clusters.driver.is_metal: true
    clusters.sutest.compute.dedicated: false
    clusters.driver.compute.dedicated: false

  not_metal:
    clusters.sutest.is_metal: false
    clusters.driver.is_metal: false

  icelake:
    extends: [metal]
    clusters.sutest.compute.dedicated: false
    clusters.driver.compute.dedicated: false
    clusters.sutest.compute.machineset.type: "Icelake"

  scale_test:
    tests.pipelines.user_count: 100
    tests.pipelines.project_count: 100
    tests.pipelines.sleep_factor: 1

  load_aware:
    extends: [light_cluster, pipeline_pi]
    clusters.sutest.compute.dedicated: false
    clusters.driver.compute.dedicated: false
    tests.pipelines.user_count: 5
    tests.pipelines.project_count: 5
    clusters.create.ocp.tags.Project: PSAP/RHODS/Pipelines/load-aware
    clusters.create.ocp.tags.TicketId: 115

  pipeline_pi:
    tests.pipelines.notebook_filename: kfp_pi.ipynb
    tests.pipelines.notebook_directory: projects/pipelines/testing/notebooks/pi

  pipeline_hash:
    tests.pipelines.notebook_filename: kfp_hash.ipynb
    tests.pipelines.notebook_directory: projects/pipelines/testing/notebooks/hash

  pipeline_timed_multistage:
    tests.pipelines.notebook_filename: kfp_timed_multistage.ipynb
    tests.pipelines.notebook_directory: projects/pipelines/testing/notebooks/timed-multistage

  pipeline_iris:
    tests.pipelines.notebook_filename: kfp_iris.ipynb
    tests.pipelines.notebook_directory: projects/pipelines/testing/notebooks/iris

  sequential:
    tests.pipelines.wait_for_run_completion: true

  concurrent:
    tests.pipelines.wait_for_run_completion: false

  smoke:
    extends: [concurrent]
    tests.pipelines.user_count: 1
    tests.pipelines.pipelines_per_user: 1
    tests.pipelines.user_pipeline_delay: 1
    tests.pipelines.project_count: 1
    tests.pipelines.runs_per_pipeline: 1
    tests.pipelines.run_delay: 1
    tests.pipelines.capture_extra_artifacts: true

  longevity:
    extends: [sequential]
    tests.pipelines.user_count: 50
    tests.pipelines.pipelines_per_user: 1
    tests.pipelines.user_pipeline_delay: 1
    tests.pipelines.project_count: 5
    tests.pipelines.runs_per_pipeline: 10
    tests.pipelines.run_delay: 300
    tests.pipelines.capture_extra_artifacts: false

  longevity_large:
    extends: [sequential]
    tests.pipelines.user_count: 50
    tests.pipelines.pipelines_per_user: 1
    tests.pipelines.user_pipeline_delay: 1
    tests.pipelines.runs_per_pipeline: 16
    tests.pipelines.run_delay: 300
    tests.pipelines.project_count: 5
    tests.pipelines.capture_extra_artifacts: false

  large_project:
    extends: [sequential]
    tests.pipelines.user_count: 50
    tests.pipelines.pipelines_per_user: 2
    tests.pipelines.user_pipeline_delay: 5
    tests.pipelines.runs_per_pipeline: 2
    tests.pipelines.run_delay: 5
    tests.pipelines.project_count: 1
    tests.pipelines.capture_extra_artifacts: false

  many_projects:
    extends: [sequential]
    tests.pipelines.user_count: 50
    tests.pipelines.pipelines_per_user: 2
    tests.pipelines.user_pipeline_delay: 5
    tests.pipelines.runs_per_pipeline: 2
    tests.pipelines.run_delay: 5
    tests.pipelines.project_count: 25
    tests.pipelines.capture_extra_artifacts: false

  large_project_concurrent:
    extends: [concurrent]
    tests.pipelines.user_count: 50
    tests.pipelines.pipelines_per_user: 2
    tests.pipelines.user_pipeline_delay: 5
    tests.pipelines.runs_per_pipeline: 2
    tests.pipelines.run_delay: 5
    tests.pipelines.project_count: 1
    tests.pipelines.capture_extra_artifacts: false

  many_projects_concurrent:
    extends: [concurrent]
    tests.pipelines.user_count: 50
    tests.pipelines.pipelines_per_user: 2
    tests.pipelines.user_pipeline_delay: 5
    tests.pipelines.runs_per_pipeline: 2
    tests.pipelines.run_delay: 5
    tests.pipelines.project_count: 25
    tests.pipelines.capture_extra_artifacts: false

  many_runs:
    extends: [sequential]
    tests.pipelines.user_count: 50
    tests.pipelines.pipelines_per_user: 1
    tests.pipelines.user_pipeline_delay: 1
    tests.pipelines.runs_per_pipeline: 8
    tests.pipelines.run_delay: 5
    tests.pipelines.project_count: 5
    tests.pipelines.capture_extra_artifacts: false

  baseline:
    extends: [sequential]
    tests.pipelines.user_count: 50
    tests.pipelines.pipelines_per_user: 2
    tests.pipelines.user_pipeline_delay: 1
    tests.pipelines.runs_per_pipeline: 2
    tests.pipelines.run_delay: 5
    tests.pipelines.project_count: 5
    tests.pipelines.capture_extra_artifacts: false

  large_mcr:
    tests.pipelines.max_concurrent_reconciles: 25

secrets:
  dir:
    name: psap-ods-secret
    env_key: PSAP_ODS_SECRET_PATH
  # name of the file containing the properties of LDAP secrets
  s3_ldap_password_file: s3_ldap.passwords
  keep_cluster_password_file: get_cluster.password
  brew_registry_redhat_io_token_file: brew.registry.redhat.io.token
  opensearch_instances: opensearch.yaml
clusters:
  metal_profiles:
    e26-h23-000-r650: icelake
  create:
    type: single # can be: single, ocp, managed
    keep: false
    name_prefix: pipelines-ci
    ocp:
      # list of tags to apply to the machineset when creating the cluster
      tags:
        TicketId: "87"
        Project: PSAP/RHODS/Pipelines
      deploy_cluster:
        target: cluster
      base_domain: psap.aws.rhperfscale.org
      version: 4.12.12
      region: us-west-2
      control_plane:
        type: m6a.xlarge
      workers:
        type: m6a.2xlarge
        count: 2

  sutest:
    is_metal: false
    lab:
      name: null
    compute:
      dedicated: true
      machineset:
        name: rhods-pipelines
        type: m6i.2xlarge
        count: null
        taint:
          key: only-rhods-pipelines
          value: "yes"
          effect: NoSchedule
  driver:
    is_metal: false
    compute:
      dedicated: true
      machineset:
        name: test-pods
        type: m6i.2xlarge
        count: null
        taint:
          key: only-test-pods
          value: "yes"
          effect: NoSchedule
  cleanup_on_exit: false
ldap:
  # Name of the LDAP identity provider.
  idp_name: RHODS_CI_LDAP
  users:
    # number of users to create
    count: 2000
    # prefix of the user names of the LDAP provider
    prefix: psapuser
rhods:
  catalog:
    image: brew.registry.redhat.io/rh-osbs/iib
    tag: 757482
    channel: fast
    version: 2.11.0
    version_name: rc1
  pipelines:
    application:
      name: sample
    notebook:
      name: SET_AT_RUNTIME
    namespace: pipelines-test
    namespace_label:
      key: dsp-scale-test
      value: "true"
    workbench:
      imagestream: s2i-generic-data-science-notebook
      imagestream_tag: 2024.1 # follow https://www.kubeflow.org/docs/components/pipelines/v2/migration/ to use a more recent image
  operator:
    # set to true to stop the RHODS operator
    stop: false

base_image:
  namespace: pipelines-scale-test
  imagestream: ci-artifacts
  repo:
    url: https://github.com/openshift-psap/topsail/
    tag: main
    ref: main
    ref_prefer_pr: true
    dockerfile_path: build/Dockerfile
  user:
    service_account: ci-artifacts
    role: cluster-admin
  minio:
    bucket_name: pipelines-scale-test-bucket
tests:
  pipelines:
    max_concurrent_reconciles: null
    deploy_pipeline: true
    notebook_filename: kfp_hello_world.ipynb
    notebook_directory: projects/pipelines/testing/notebooks/hello-world
    project_count: 2
    user_count: 2
    pipelines_per_user: 1
    runs_per_pipeline: 1
    run_delay: 10
    wait_for_run_completion: false
    user_pipeline_delay: 5
    sleep_factor: 1
    user_batch_size: 1
    capture_extra_artifacts: false
matbench:
  preset: null
  workload: projects.pipelines.visualizations.rhods-pipelines
  config_file: scale_test.yaml
  download:
    mode: prefer_cache
    url:
    url_file:
    # if true, copy the results downloaded by `matbench download` into the artifacts directory
    save_to_artifacts: false
  ignore_exit_code: true
  # directory to plot. Set by notebook_scale_test.sh before launching the visualization
  test_directory: null
  lts:
    generate: true
    horreum:
      test_name: null
    opensearch:
      export:
        enabled: false
        enabled_on_replot: false
        fail_test_on_fail: false
      fail_test_on_fail: false
      instance: smoke
      index: pipelines
      index_prefix: ""
    regression_analyses:
      enabled: false
      # if the regression analyses fail, mark the test as failed
      fail_test_on_regression: false
