apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: granite-3-0-8b-instruct-

resources:
- ../../base

patches:
- path: patch.yaml
  target:
    kind: InferenceService
  options:
    allowNameChange: true

