---
apiVersion: v1
kind: ConfigMap
metadata:
  name: s3cmd-config
data:
  s3cfg: |
    # Setup endpoint
    host_base = $S3_HOST_BASE
    host_bucket = $S3_HOST_BUCKET
    bucket_location = us-east-1
    use_https = False

    # Setup access keys
    access_key = $S3_ACCESS_KEY
    secret_key = $S3_SECRET_KEY
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    deployment: api-scale-test
  name: api-scale-test
spec:
  parallelism: 1
  completions: 1
  activeDeadlineSeconds: 18000
  backoffLimit: 0
  completionMode: Indexed
  template:
    metadata:
      name: api-scale-test
      labels:
        deployment: api-scale-test
    spec:
      securityContext:
        runAsUser: 1001
      containers:
      - image: "{{ rhods_api_scale_test_image }}"
        imagePullPolicy: Always
        name: main
        command: [bash, -ce]
        args:
        - |
           mkdir -p "$ARTIFACT_DIR"
           python3 -u /mnt/rhods-notebook-api-scale-test-entrypoint/entrypoint.py
        env:
        - name: ARTIFACT_DIR
          value: /mnt/shared-dir/api-scale-test
        - name: TEST_USERS_IDP_NAME
          value: "{{ rhods_notebook_api_scale_test_idp_name }}"
        - name: TEST_USERS_USERNAME_PREFIX
          value: "{{ rhods_notebook_api_scale_test_username_prefix }}"
        - name: RHODS_VERSION
          value: "{{ rhods_version_cmd.stdout }}"
        - name: ODH_DASHBOARD_URL
          value: "https://{{ rhods_dashboard_hostname_cmd.stdout }}"
        - name: CREDS_FILE
          value: "/mnt/rhods-scale-test-credentials/secret.properties"
        - name: API_SCALE_TEST_NAME
          value: "{{ rhods_notebook_api_scale_test_test_name }}"
        - name: NOTEBOOK_IMAGE_NAME
          value: "{{ rhods_notebook_api_scale_test_ods_ci_notebook_image_name }}"
        - name: LOCUST_LOCUSTFILE
          value: "/mnt/rhods-notebook-api-scale-test-entrypoint/locustfile.py"
        - name: LOCUST_DIR
          value: "/mnt/rhods-notebook-api-scale-test-entrypoint"
        - name: LOCUST_USERS
          value: "{{ rhods_notebook_api_scale_test_user_count }}"
        - name: LOCUST_RUN_TIME
          value: "{{ rhods_notebook_api_scale_test_run_time }}"
        - name: LOCUST_SPAWN_RATE
          value: "{{ rhods_notebook_api_scale_test_spawn_rate }}"
        volumeMounts:
        - name: shared-dir
          mountPath: /mnt/shared-dir
        - name: rhods-notebook-api-scale-test-entrypoint
          mountPath: /mnt/rhods-notebook-api-scale-test-entrypoint
        - name: rhods-scale-test-credentials
          mountPath: /mnt/rhods-scale-test-credentials
      - image: "{{ rhods_artifacts_exporter_image }}"
        name: artifacts-exporter
        command: ['bash', '/mnt/rhods-notebook-api-scale-test-entrypoint/artifacts-exporter.sh']
        env:
        - name: ARTIFACTS_COLLECTED
          value: "all"
        - name: ARTIFACT_DIR
          value: "/mnt/shared-dir/api-scale-test"
        - name: CREDS_FILE
          value: "/mnt/rhods-scale-test-credentials/secret.properties"
        - name: BUCKET_DEST_DIR
          value: "api-scale-test"
        volumeMounts:
        - name: s3cmd-config
          mountPath: /mnt/s3-config
        - name: shared-dir
          mountPath: /mnt/shared-dir
        - name: rhods-scale-test-credentials
          mountPath: /mnt/rhods-scale-test-credentials
        - name: rhods-notebook-api-scale-test-entrypoint
          mountPath: /mnt/rhods-notebook-api-scale-test-entrypoint
      restartPolicy: Never
{% if rhods_notebook_api_scale_test_toleration_key|length %}
      tolerations:
      - effect: NoSchedule
        key: {{ rhods_notebook_api_scale_test_toleration_key }}
        operator: Exists
{% endif %}
      volumes:
      - name: rhods-scale-test-credentials
        secret:
          secretName: rhods-scale-test-credentials
      - name: s3cmd-config
        configMap:
          name: s3cmd-config
      - name: rhods-notebook-api-scale-test-entrypoint
        configMap:
          name: rhods-notebook-api-scale-test-entrypoint
      - name: shared-dir
        emptyDir: {}
