apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: japanese-llama-2-7b-instruct-

resources:
- ../../base

patches:
- path: patch.yaml  
  target:
    kind: InferenceService
  options:
    allowNameChange: true
