---
- name: Fail if artifact_dir is not defined
  fail: msg="'artifact_dir' must be defined before running this role"
  when: artifact_dir is undefined

- name: Fail if artifact_extra_logs_dir is not defined
  fail: msg="'artifact_extra_logs_dir' must be defined before running this role"
  when: artifact_extra_logs_dir is undefined

- block:
  - name: Fetch 'openshift_release' value and check dependencies
    # see the 'fail' message below before modifying this command,
    # it verifies that the main dependencies are met.
    shell:
      set -eo pipefail;
      oc version -o json
      | jq --raw-output '.openshiftVersion'
    register: ocp_version
    failed_when: ocp_version.stdout == 'nul' or ocp_version.stdout == ""
  rescue:
  - name: Fail because of a dependency issue
    fail:
      msg: |
        Failed to fetch OpenShift version. Please verify the failure message above and double check:
          1. that `KUBECONFIG` is properly set ({{ lookup('env', 'KUBECONFIG') }})
          2. that `oc` is available in the PATH
          3. that `jq` is available in the PATH
          4. that `oc` and `KUBECONFIG` are able to access the OpenShift cluster

- name: Get openshift major and minor version
  shell:
    set -eo pipefail;
    echo "{{ ocp_version.stdout }}" | tr '.' '\n' | head -2
  register: ocp_major_minor_version

- name: Store openshift major and minor version
  set_fact:
    openshift_release_major: "{{ ocp_major_minor_version.stdout[0] }}"
    openshift_release_minor: "{{ ocp_major_minor_version.stdout[2] }}"

- name: 'Store openshift_release={{ ocp_version.stdout }}'
  set_fact:
    openshift_release: "{{ openshift_release_major }}.{{ openshift_release_minor }}"

- name: Store openshift major and minor version
  debug: msg="openshift_release_major='{{ openshift_release_major }}', openshift_release_minor='{{ openshift_release_minor }}'"
