---
- name: Validate the models
  loop: "{{ kserve_validate_model_inference_service_names }}"
  loop_control:
    loop_var: kserve_validate_model_inference_service_name
  include_tasks: validate_model.yaml
