kind: GrafanaDatasource
apiVersion: grafana.integreatly.org/v1beta1
metadata:
  name: thanos
spec:
  resyncPeriod: 10m
  uid: prometheus
  valuesFrom:
    - targetPath: secureJsonData.httpHeaderValue1
      valueFrom:
        secretKeyRef:
         name: grafana-token
         key: token
  datasource:
    access: proxy
    isDefault: true
    jsonData:
        httpHeaderName1: Authorization
        timeInterval: 5s
        tlsSkipVerify: true # TODO: don't skip tls verification
    secureJsonData:
      httpHeaderValue1: "Bearer ${token}"
    name: prometheus
    type: prometheus
    url: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
  instanceSelector:
    matchLabels:
      dashboards: grafana
  plugins:
    - name: grafana-clock-panel
      version: 1.3.0
