exclude_paths:
  - .github

skip_list:
  # Hide "wrong indentation: expected 4 but found 2 (indentation)"
  # until we find out how to properly configure it
  - 'yaml[indentation]'
  - 'yaml[line-length]'
  # Do not force galaxy info in meta/main.yml
  - 'meta-no-info'
  # Hide "Commands should not change things if nothing needs doing"
  - 'no-changed-when'
  # Hide "Role name 'xxx_yyy' does not match ``^[a-z][a-z0-9_]+$`` pattern"
  - 'role-name'
  ## The following Ansible lint rules are the ones that are currently
  ## part of the main lint checks that are not adresses in this repo
  ## The following skip rules represent 3143 failure(s), 12 warning(s) on 852 files.
  - 'command-instead-of-module'
  - 'command-instead-of-shell'
  - 'deprecated-local-action'
  - 'no-free-form'
  - 'chema[meta]'
  - 'ignore-errors'
  - 'fqcn'
  - 'var-naming[no-role-prefix]'
