---
- name: Check if AWS EFS CSI Operator is installed
  command:
    oc get subscription.operators.coreos.com -A -oname
       -loperators.coreos.com/aws-efs-csi-driver-operator.openshift-operators
  failed_when: false
  register: has_aws_efs_csi_cmd

- name: Run the operator deployment colr
  when: not has_aws_efs_csi_cmd.stdout
  include_role:
    name: cluster_deploy_operator
  vars:
    cluster_deploy_operator_catalog: redhat-operators
    cluster_deploy_operator_manifest_name: aws-efs-csi-driver-operator
    cluster_deploy_operator_all_namespaces: "True"
    cluster_deploy_operator_namespace: openshift-operators

- name: Create the AWS EFS filesystem
  include_tasks: aws-efs.yaml

- name: Print the AWS EFS fs ID
  command: echo "{{ aws_efs_fs_id }}"

- name: Instantiate the ClusterCSIDriver template
  template:
    src: "{{ cluster_deploy_aws_efs_csi_driver }}"
    dest: "{{ artifact_extra_logs_dir }}/csi-driver.yml"
    mode: '0400'

- name: Create the ClusterCSIDriver resource
  command: oc apply -f "{{ artifact_extra_logs_dir }}/csi-driver.yml"

- name: Instantiate the StorageClass template
  template:
    src: "{{ cluster_deploy_aws_efs_storage_class }}"
    dest: "{{ artifact_extra_logs_dir }}/storage-class.yml"
    mode: '0400'

- name: Create the StorageClass resource
  command: oc apply -f "{{ artifact_extra_logs_dir }}/storage-class.yml"
