- name: Create the src artifacts directory
  file:
    path: "{{ artifact_extra_logs_dir }}/src/"
    state: directory
    mode: '0755'

- name: Define the Trimaran setup config
  set_fact:
    trimaran_setup_config: "{{ artifact_extra_logs_dir }}/src/trimaran-templated-config.yaml"

- name: Configure Trimaran options
  template:
    src: "{{ trimaran_setup_template }}"
    dest: "{{ trimaran_setup_config }}"

- name: Delete Trimaran resources
  command: 
    oc delete -f {{ trimaran_setup_config }} --ignore-not-found
