---
# See if SRO has been installed to the user's cluster
- name: Check if Special Resource Operator (SRO) has already been installed
  block:
    - name: Checking if the Special Resource Operator (SRO) has already been installed to your cluster
      shell: 'oc get crds | grep specialresources.sro.openshift.io'
      register: sro_installation
  rescue:
    - name: Special Resource Operator not installed to your cluster.
      debug:
        msg: "The Special Resource Operator has not been installed to your cluster. Could not find SRO custom resources."

# If forcing a reinstall or doing a fresh install, then call the following block
- block:

  # Download the git repo
  - include_tasks: clone_sro_git_repo.yaml 

  # Install dependencies and prepare for build
  - include_tasks: prepare_deployment.yaml

  # Call the below playbook when the user is forcing a reinstall of NFD
  - include_tasks: uninstall_sro.yaml 
    when: (sro_installation.stdout != '' and reinstall == 'yes') or (sro_installation.stdout != '' and user_mode == 'uninstall')

  # Deploy the operator
  - include_tasks: deploy_operator.yaml
    when: user_mode == 'install'

  when: (sro_installation.stdout == '') or (sro_installation.stdout != '' and reinstall == 'yes') or (sro_installation.stdout != '' and user_mode == 'uninstall')
