---
# Uninstall (undeploy) SRO
- name: Undeploying SRO operator
  block:
    - name: Attempting to undeploy the SRO operator. Waiting {{ task_timeout }}s...
      make:
        chdir: '{{ sro_download_path }}'
        target: 'undeploy'
      async: '{{ task_timeout }}'
      poll: 10
      register: sro_undeployment_output
      failed_when: sro_undeployment_output.rc == 1
  rescue:
    - name: Undeployment failed
      debug:
        msg: 'Could not undeploy the operator. Likely, the "openshift-sro" namespace is stuck in terminating. This is an OpenShift issue. Please either increase the "task_timeout" value or try the following solution to force undeployment -- github.com/kubernetes/kubernetes/issues/60807#issuecomment-408599873 -- although you may need to follow instructions here -- github.com/kubernetes/kubernetes/issues/60807#issuecomment-410260006 -- You may also need to check if the SRO operator was partially undeployed. Partial undeployment can result in this error, too.'
    - meta: end_play
