---
gpu_operator_git_repo: ""
gpu_operator_git_ref: ""
gpu_operator_image_tag_uid: ""
gpu_operator_image_tag: "gpu-operator-{{ gpu_operator_image_tag_uid }}"
gpu_operator_bundle_image_tag: "gpu-operator-bundle-{{ gpu_operator_image_tag_uid }}"
