- name: Ensure that NFD labeled some nodes
  block:
  - name: Ensure that NFD labeled some nodes
    command: oc get nodes -lfeature.node.kubernetes.io/system-os_release.ID=rhel
    register: has_nfd_nodes
    failed_when: has_nfd_nodes.stdout == ""

  rescue:
  - name: Check if NFD CR exists (debug)
    command: oc get NodeFeatureDiscovery -A
    failed_when: false

  - name: Fail because nodes do not have NFD labels
    fail: msg="Fail because nodes do not have NFD labels"
