---

# See if Kubeflow has been installed to the cluster already
- name: Check if Kubeflow has already been installed
  block:
    - name: Checking if Kubeflow has already been installed to your cluster
      shell: 'oc get ns kubeflow'
      register: odh_installation
  rescue:
    - name: Kubeflow not installed to your cluster.
      debug:
        msg: "Kubeflow (via Open Data Hub) has not been installed to your cluster. Could not find Kubeflow resources."

# If forcing a reinstall or doing a fresh install, then call the following block
- block:

  # Install required packages
  - include_tasks: install_required_pkgs.yaml

  # Download the git repo
  - include_tasks: clone_odh_git_repo.yaml

  # Build the kfdef file for installing Kubeflow to the cluster or deleting it from the cluster
  - include_tasks: build_kfdef.yaml

  # Call the below playbook when the user is forcing a reinstall of NFD
  - include_tasks: uninstall_odh.yaml
    when: >
      (odh_installation.stdout != '' and force_reinstall == 'yes') or
      (odh_installation.stdout != '' and user_mode == 'uninstall')

  # Deploy the operator
  - include_tasks: deploy_operator.yaml
    when: >
      (user_mode == 'install') or
      (user_mode == 'ci')

  # Remove the NFD download folder
  - name: Remove Open Data Hub git repo
    file:
      state: absent
      path: '{{ odh_download_path }}'

  when: >
    (odh_installation.stdout == '') or
    (odh_installation.stdout != '' and force_reinstall == 'yes') or
    (odh_installation.stdout != '' and user_mode == 'uninstall') or
    ("(NotFound)" in odh_installation.stdout)
