---
- name: Get Prometheus Pod name
  command:
    oc get pods
       -l {{ cluster_prometheus_db_label }}
       -n {{ cluster_prometheus_db_namespace }}
       --sort-by=.metadata.creationTimestamp
       -ojsonpath='{.items[0].metadata.name}'
  register: prometheus_pod_name_cmd
  failed_when: not prometheus_pod_name_cmd.stdout

- name: Extract Prometheus database from the Pod
  shell:
    oc exec -c prometheus -n "{{ cluster_prometheus_db_namespace }}" "{{ prometheus_pod_name_cmd.stdout }}" -- tar cvzf - -C "{{ cluster_prometheus_db_directory }}" . > "{{ artifact_extra_logs_dir }}/{{ cluster_prometheus_db_dump_name_prefix }}.tar.gz"
  register: extract_prometheus_db
  # for tar, 0 means OK, 1 means file changed as we read it (we ignore it, 'Prometheus updates files atomically')
  failed_when: extract_prometheus_db.rc > 1

- name: Save the cluster nodes along with the Prom database
  shell:
    oc get nodes -ojson > "{{ artifact_extra_logs_dir }}/nodes.json"
