---
- name: Create the namespace for the NFD Operator
  command: oc apply -f "{{ nfd_operator_namespace }}"
          
- name: Create the OperatorGroup object
  block:
    - name: apply operatorGroup manifest 
      command: oc apply -f "{{ nfd_operator_operatorgroup }}"
      register: test_operatorgroup
  rescue:
    - name: Failed when creating the OperatorGroup object for the NFD Operator
      fail:
        msg: "{{ test_operatorgroup }}"
          
- name: Create the OperatorHub subscription for the NFD Operator
  block:
    - name: apply operatorhub subscription manifest 
      command: oc apply -f "{{ nfd_operator_operatorhub_sub }}"
      register: nfd_operatorhub_sub
  rescue:
    - name: Failed when creating the test operatorHub subscription for the NFD Operator
      fail:
        msg: "{{ nfd_operatorhub_sub }}"
          
- name: Create the NodeFeatureDiscovery CR for the NFD Operator
  block:
    - name: apply NodeFeatureDiscovery manifest 
      command: oc apply -f "{{ nfd_operator_crd }}"
      register: nfd_cr
      until: nfd_cr.rc != 1
      retries: 5
      delay: 5
  rescue:
    - name: Failed when creating the test clusterpolicy CR for the GPU Operator
      fail:
        msg: "{{ nfd_cr }}"

- name: Create the namespace for the GPU Operator
  block:
    - name: apply namespace manifest 
      command: oc apply -f "{{ gpu_operator_namespace }}"
      register: test_namespace
  rescue:
    - name: Failed when creating the test namespace for the GPU Operator
      fail:
        msg: "{{ test_namespace }}"
          
- name: Create the OperatorHub subscription for the GPU Operator
  block:
    - name: apply operatorhub subscription manifest 
      command: oc apply -f "{{ gpu_operator_operatorhub_sub }}"
      register: test_operatorhub_sub
  rescue:
    - name: Failed when creating the OperatorHub subscription for the GPU Operator
      fail:
        msg: "{{ test_operatorhub_sub }}"
          
- name: Create the clusterPolicy CR for the GPU Operator
  block:
    - name: apply clusterpolicy manifest 
      command: oc apply -f "{{ gpu_operator_crd }}"
      register: test_clusterpolicy_cr
      until: test_clusterpolicy_cr.rc != 1
      retries: 5
      delay: 5
  rescue:
    - name: Failed when creating the clusterpolicy CR for the GPU Operator
      fail:
        msg: "{{ test_clusterpolicy_cr }}"
